### ISSUE TITLE
Navigator does not initialize

### ISSUE THREAD

**Issue by arperon** [Mayavan/Turtlebot_Path_Planning_RRT#1]
Hello, good day! 
I have installed and initialized the RRT star navigator following the instructions on "ReadMe" file. But when I tried to run the command "$ rosrun project5 Main" ("project5" is the name of the package), I only get the message: 
"No Data
 Segmentation fault (core dumped)"
Please, could you help me? 
Thanks in advance!

**Comment by Mayavan** [comment]
Hi,

The path to the map file was hard coded. I have updated the repo so that it could accept file location as parameter.

**Comment by arperon** [comment]
Dear Mayavan, 
Thank you very much for your attention and help.
Best regards!
